name: Run Hentai Manga Bot

on:
  workflow_dispatch:  # Keep for manual triggering
  schedule:
    - cron: "30 3 * * *"  # Run daily at 3:30 AM UTC (9:00 AM IST)

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      run: python src/main.py

    - name: Commit and push progress changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add config/progress.json
        git commit -m "Update progress.json with latest chapter numbers" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs
        path: bot.log
